In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
df1 = pd.read_csv('adultDataset.csv')
df1.head()

age workclass  fnlwgt     education  education.num marital.status  \
0   90         ?   77053       HS-grad              9        Widowed   
1   82   Private  132870       HS-grad              9        Widowed   
2   66         ?  186061  Some-college             10        Widowed   
3   54   Private  140359       7th-8th              4       Divorced   
4   41   Private  264663  Some-college             10      Separated   

          occupation   relationship   race     sex  capital.gain  \
0                  ?  Not-in-family  White  Female             0   
1    Exec-managerial  Not-in-family  White  Female             0   
2                  ?      Unmarried  Black  Female             0   
3  Machine-op-inspct      Unmarried  White  Female             0   
4     Prof-specialty      Own-child  White  Female             0   

   capital.loss  hours.per.week native.country income  
0          4356              40  United-States  <=50K  
1          4356              18  United-States  <=50K  
2          4356              40  United-States  <=50K  
3          3900              40  United-States  <=50K  
4          3900              40  United-States  <=50K

In [3]:
df1.tail()

age workclass  fnlwgt     education  education.num      marital.status  \
32556   22   Private  310152  Some-college             10       Never-married   
32557   27   Private  257302    Assoc-acdm             12  Married-civ-spouse   
32558   40   Private  154374       HS-grad              9  Married-civ-spouse   
32559   58   Private  151910       HS-grad              9             Widowed   
32560   22   Private  201490       HS-grad              9       Never-married   

              occupation   relationship   race     sex  capital.gain  \
32556    Protective-serv  Not-in-family  White    Male             0   
32557       Tech-support           Wife  White  Female             0   
32558  Machine-op-inspct        Husband  White    Male             0   
32559       Adm-clerical      Unmarried  White  Female             0   
32560       Adm-clerical      Own-child  White    Male             0   

       capital.loss  hours.per.week native.country income  
32556             0              40  United-States  <=50K  
32557             0              38  United-States  <=50K  
32558             0              40  United-States   >50K  
32559             0              40  United-States  <=50K  
32560             0              20  United-States  <=50K

In [4]:
print(df1.info())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             32561 non-null  int64 
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   education       32561 non-null  object
 4   education.num   32561 non-null  int64 
 5   marital.status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital.gain    32561 non-null  int64 
 11  capital.loss    32561 non-null  int64 
 12  hours.per.week  32561 non-null  int64 
 13  native.country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB
None


In [5]:
# Drop rows with '?' in any column
df_cleaned = df1[~df1.astype(str).apply(lambda x: x.str.contains(r'\?')).any(axis=1)]
df_cleaned.head()

age workclass  fnlwgt     education  education.num marital.status  \
1   82   Private  132870       HS-grad              9        Widowed   
3   54   Private  140359       7th-8th              4       Divorced   
4   41   Private  264663  Some-college             10      Separated   
5   34   Private  216864       HS-grad              9       Divorced   
6   38   Private  150601          10th              6      Separated   

          occupation   relationship   race     sex  capital.gain  \
1    Exec-managerial  Not-in-family  White  Female             0   
3  Machine-op-inspct      Unmarried  White  Female             0   
4     Prof-specialty      Own-child  White  Female             0   
5      Other-service      Unmarried  White  Female             0   
6       Adm-clerical      Unmarried  White    Male             0   

   capital.loss  hours.per.week native.country income  
1          4356              18  United-States  <=50K  
3          3900              40  United-States  <=50K  
4          3900              40  United-States  <=50K  
5          3770              45  United-States  <=50K  
6          3770              40  United-States  <=50K

In [6]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30162 entries, 1 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             30162 non-null  int64 
 1   workclass       30162 non-null  object
 2   fnlwgt          30162 non-null  int64 
 3   education       30162 non-null  object
 4   education.num   30162 non-null  int64 
 5   marital.status  30162 non-null  object
 6   occupation      30162 non-null  object
 7   relationship    30162 non-null  object
 8   race            30162 non-null  object
 9   sex             30162 non-null  object
 10  capital.gain    30162 non-null  int64 
 11  capital.loss    30162 non-null  int64 
 12  hours.per.week  30162 non-null  int64 
 13  native.country  30162 non-null  object
 14  income          30162 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [7]:
df_cleaned.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country',
       'income'],
      dtype='object')

Checking null values

In [8]:
df_cleaned.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

Calculating stats of each column


In [9]:
df_cleaned.describe()

age        fnlwgt  education.num  capital.gain  capital.loss  \
count  30162.000000  3.016200e+04   30162.000000  30162.000000  30162.000000   
mean      38.437902  1.897938e+05      10.121312   1092.007858     88.372489   
std       13.134665  1.056530e+05       2.549995   7406.346497    404.298370   
min       17.000000  1.376900e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.176272e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.784250e+05      10.000000      0.000000      0.000000   
75%       47.000000  2.376285e+05      13.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       hours.per.week  
count    30162.000000  
mean        40.931238  
std         11.979984  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

Training and testing data Split And Transforming the Classification
Columns using LabelEncoder

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
pd.__version__

'2.2.2'

In [12]:
pd.options.mode.copy_on_write = True 

In [13]:
lb = LabelEncoder()
df_cleaned['workclass'] = lb.fit_transform(df_cleaned['workclass'])
df_cleaned['education'] = lb.fit_transform(df_cleaned['education'])
df_cleaned['marital.status'] = lb.fit_transform(df_cleaned['marital.status'])
df_cleaned['occupation'] = lb.fit_transform(df_cleaned['occupation'])
df_cleaned['relationship'] = lb.fit_transform(df_cleaned['relationship'])
df_cleaned['race'] = lb.fit_transform(df_cleaned['race'])
df_cleaned['sex'] = lb.fit_transform(df_cleaned['sex'])
df_cleaned['native.country'] = lb.fit_transform(df_cleaned['native.country'])

In [14]:
x=df_cleaned[['age', 'workclass', 'fnlwgt', 'education', 'education.num',
       'marital.status', 'occupation', 'relationship', 'race', 'sex',
       'capital.gain', 'capital.loss', 'hours.per.week', 'native.country']]
y=df_cleaned['income']
print(type(x))
print(type(y))
print(x.shape)
print(y.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
(30162, 14)
(30162,)


In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train,x_test,y_train,y_test = train_test_split(x,y)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(22621, 14)
(7541, 14)
(22621,)
(7541,)


Decision Tree Classifier


In [17]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [18]:
def gen_metrics(ytest,ypred):
    cm = confusion_matrix(ytest,ypred)
    print('confusion matrix\n',cm)
    print('Classification report\n',classification_report(ytest,ypred))
    print('Acc Score', accuracy_score(ytest,ypred))

In [19]:
from sklearn.tree import DecisionTreeClassifier

In [20]:
m1 = DecisionTreeClassifier()
m1.fit(x_train,y_train)


DecisionTreeClassifier()

In [21]:
#Accuracy
print('Training Score',m1.score(x_train,y_train))
print('Testing Score',m1.score(x_test,y_test))


Training Score 1.0
Testing Score 0.8069221588648721


In [22]:
ypred_m1 = m1.predict(x_test)
print(ypred_m1)

['>50K' '<=50K' '<=50K' ... '<=50K' '<=50K' '<=50K']


In [23]:
gen_metrics(y_test,ypred_m1)

confusion matrix
 [[4834  738]
 [ 718 1251]]
Classification report
               precision    recall  f1-score   support

       <=50K       0.87      0.87      0.87      5572
        >50K       0.63      0.64      0.63      1969

    accuracy                           0.81      7541
   macro avg       0.75      0.75      0.75      7541
weighted avg       0.81      0.81      0.81      7541

Acc Score 0.8069221588648721


Validation

In [70]:
pre0 = 4834/(4834+718)
pre1 = 1251/(1251+738)
rec0 = 4834/(4834+738)
rec1 = 1251/(1251+718)
print('Pre0',pre0)
print('Pre1',pre1)
print('Rec0',rec0)
print('Rec1',rec1)


Pre0 0.8706772334293948
Pre1 0.6289592760180995
Rec0 0.8675520459440057
Rec1 0.6353478923311325


In [71]:
f1s0 = 2*pre0*rec0/(pre0+rec0)
f1s1 = 2*pre1*rec1/(pre1+rec1)
print('F1_Score0',f1s0)
print('F1_Score1',f1s1)


F1_Score0 0.8691118302768789
F1_Score1 0.6321374431531077


In [72]:
acc = (4834+1251)/(4834+738+718+1251)
print('Accuracy',acc)


Accuracy 0.8069221588648721


Percentage of misclasification

In [73]:
# Misclassification Rate = incorrect predictions / total predictions
# Misclassification Rate = (false positive + false negative) / (total predictions)
MR = (718+738)/(4834+738+718+1251)
print('Percentage of Misclassification : ',MR*100, '%')

Percentage of Misclassification :  19.307784113512795 %


Random Forest Classifier

In [28]:
from sklearn.ensemble import RandomForestClassifier


In [29]:
m2 = RandomForestClassifier()
m2.fit(x_train,y_train)


RandomForestClassifier()

In [30]:
print('Training Score',m2.score(x_train,y_train))
print('Testing Score',m2.score(x_test,y_test))


Training Score 1.0
Testing Score 0.8574459620739955


In [31]:
ypred_m2 = m2.predict(x_test)
print(ypred_m2)


['<=50K' '<=50K' '<=50K' ... '<=50K' '<=50K' '<=50K']


In [32]:
gen_metrics(y_test,ypred_m2)

confusion matrix
 [[5196  376]
 [ 699 1270]]
Classification report
               precision    recall  f1-score   support

       <=50K       0.88      0.93      0.91      5572
        >50K       0.77      0.64      0.70      1969

    accuracy                           0.86      7541
   macro avg       0.83      0.79      0.80      7541
weighted avg       0.85      0.86      0.85      7541

Acc Score 0.8574459620739955


Validation

In [33]:
pre0 = 5196/(5196+699)
pre1 = 1270/(1270+376)
rec0 = 5196/(5196+376)
rec1 = 1270/(1270+699)
print('Pre0',pre0)
print('Pre1',pre1)
print('Rec0',rec0)
print('Rec1',rec1)


Pre0 0.8814249363867684
Pre1 0.7715674362089915
Rec0 0.9325197415649676
Rec1 0.6449974606399187


In [34]:
f1s0 = 2*pre0*rec0/(pre0+rec0)
f1s1 = 2*pre1*rec1/(pre1+rec1)
print('F1_Score0',f1s0)
print('F1_Score1',f1s1)


F1_Score0 0.9062527252114764
F1_Score1 0.7026279391424619


In [36]:
acc = (5196+1270)/(5196+376+699+1270)
print('Accuracy',acc)

Accuracy 0.8574459620739955


Percentage of Misclassification

In [37]:
# Misclassification Rate = incorrect predictions / total predictions
# Misclassification Rate = (false positive + false negative) / (total predictions)
MR = (699+376)/(5196+376+699+1270)
print('Percentage of Misclassification : ',MR*100, '%')

Percentage of Misclassification :  14.255403792600452 %


KNN Classifier

In [38]:
from sklearn.neighbors import KNeighborsClassifier

In [39]:
m3 = KNeighborsClassifier()
m3.fit(x_train,y_train)


KNeighborsClassifier()

In [40]:
#Accuracy
print('Training Score',m3.score(x_train,y_train))
print('Testing Score',m3.score(x_test,y_test))

Training Score 0.8312187790106538
Testing Score 0.7634266012465191


In [41]:
ypred_m3 = m3.predict(x_test)
print(ypred_m3)

['<=50K' '<=50K' '<=50K' ... '<=50K' '<=50K' '<=50K']


In [42]:
gen_metrics(y_test,ypred_m3)


confusion matrix
 [[5145  427]
 [1357  612]]
Classification report
               precision    recall  f1-score   support

       <=50K       0.79      0.92      0.85      5572
        >50K       0.59      0.31      0.41      1969

    accuracy                           0.76      7541
   macro avg       0.69      0.62      0.63      7541
weighted avg       0.74      0.76      0.74      7541

Acc Score 0.7634266012465191


Validation

In [43]:
pre0 = 5145/(5145+1357)
pre1 = 612/(612+427)
rec0 = 5145/(5145+427)
rec1 = 612/(612+1357)
print('Pre0',pre0)
print('Pre1',pre1)
print('Rec0',rec0)
print('Rec1',rec1)

Pre0 0.7912949861581052
Pre1 0.5890279114533205
Rec0 0.9233668341708543
Rec1 0.31081767394616555


In [44]:
f1s0 = 2*pre0*rec0/(pre0+rec0)
f1s1 = 2*pre1*rec1/(pre1+rec1)
print('F1_Score0',f1s0)
print('F1_Score1',f1s1)

F1_Score0 0.8522444922974988
F1_Score1 0.40691489361702127


In [45]:
acc = (5145+612)/(5145+427+1357+612)
print('Accuracy',acc)

Accuracy 0.7634266012465191


Percentage of Misclassification

In [46]:
# Misclassification Rate = incorrect predictions / total predictions
# Misclassification Rate = (false positive + false negative) / (total predictions)
MR = (1357+427)/(5145+427+1357+612)
print('Percentage of Misclassification : ',MR*100, '%')

Percentage of Misclassification :  23.657339875348097 %


Logistic Regression


In [47]:
from sklearn.linear_model import LogisticRegression


In [48]:
m4 = LogisticRegression(max_iter=10000)
m4.fit(x_train,y_train)

C:\Users\Pratinav\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=10000)

In [49]:
#Accuracy
print('Training Score',m4.score(x_train,y_train))
print('Testing Score',m4.score(x_test,y_test))


Training Score 0.8070377083241236
Testing Score 0.801617822569951


In [50]:
ypred_m4 = m4.predict(x_test)
print(ypred_m4)

['<=50K' '<=50K' '<=50K' ... '<=50K' '<=50K' '<=50K']


In [51]:
gen_metrics(y_test,ypred_m4)


confusion matrix
 [[5304  268]
 [1228  741]]
Classification report
               precision    recall  f1-score   support

       <=50K       0.81      0.95      0.88      5572
        >50K       0.73      0.38      0.50      1969

    accuracy                           0.80      7541
   macro avg       0.77      0.66      0.69      7541
weighted avg       0.79      0.80      0.78      7541

Acc Score 0.801617822569951


In [52]:
m = m4.coef_
c = m4.intercept_
print('Coefficient',m)
print('Intercept or constant',c)

Coefficient [[ 9.86259210e-03 -1.25455231e-01 -1.20316030e-06 -2.91212466e-02
   2.25473199e-01 -2.83310171e-01 -1.57697352e-02 -3.25789965e-01
  -1.27528127e-01  2.60962725e-01  3.10883122e-04  6.65942175e-04
   8.47954178e-03 -4.82465868e-02]]
Intercept or constant [-0.49478894]


In [53]:
print('Testing Score',m4.score(x_test,y_test))
print('Accuracy Score',accuracy_score(y_test,ypred_m4))

Testing Score 0.801617822569951
Accuracy Score 0.801617822569951


In [55]:
def sigmoid(X,m,c):
    logit = 1/(1 + np.exp(-(m*X+c)))
    print(logit)


In [56]:
sigmoid (0.077316,m,c) #example using any value taken as X

[[0.37894551 0.3764864  0.37876604 0.37823642 0.3828766  0.37362576
  0.37847921 0.37285744 0.37644878 0.38352514 0.37877172 0.37877818
  0.37892034 0.37788873]]


Validation

In [57]:
pre0 = 5304/(5304+1228)
pre1 = 741/(741+268)
rec0 = 5304/(5304+268)
rec1 = 741/(741+1228)
print('Pre0',pre0)
print('Pre1',pre1)
print('Rec0',rec0)
print('Rec1',rec1)

Pre0 0.8120024494794856
Pre1 0.734390485629336
Rec0 0.9519023689877961
Rec1 0.37633316404266126


In [58]:
f1s0 = 2*pre0*rec0/(pre0+rec0)
f1s1 = 2*pre1*rec1/(pre1+rec1)
print('F1_Score0',f1s0)
print('F1_Score1',f1s1)


F1_Score0 0.8764044943820225
F1_Score1 0.49764942914707855


In [59]:
acc = (5304+741)/(5304+268+1228+741)
print('Accuracy',acc)


Accuracy 0.801617822569951


Percentage of Misclassification

In [60]:
# Misclassification Rate = incorrect predictions / total predictions
# Misclassification Rate = (false positive + false negative) / (total predictions)
MR = (1228+268)/(5304+268+1228+741)
print('Percentage of Misclassification : ',MR*100, '%')

Percentage of Misclassification :  19.838217743004908 %


SVM Classifier

In [61]:
from sklearn.svm import LinearSVC

In [62]:
m5 = LinearSVC(random_state=0, tol=1e-5, dual=False)
m5.fit(x_train, y_train.ravel())

C:\Users\Pratinav\AppData\Local\Temp\ipykernel_12612\1488667663.py:2: FutureWarning: Series.ravel is deprecated. The underlying array is already 1D, so ravel is not necessary.  Use `to_numpy()` for conversion to a numpy array instead.
  m5.fit(x_train, y_train.ravel())


LinearSVC(dual=False, random_state=0, tol=1e-05)

In [63]:
#Accuracy
print('Training Score',m5.score(x_train,y_train))
print('Testing Score',m5.score(x_test,y_test))


Training Score 0.8035895848989877
Testing Score 0.7948547937939265


In [64]:
ypred_m5 = m5.predict(x_test)
print(ypred_m5)


['<=50K' '<=50K' '<=50K' ... '<=50K' '<=50K' '<=50K']


In [65]:
gen_metrics(y_test,ypred_m5)

confusion matrix
 [[5337  235]
 [1312  657]]
Classification report
               precision    recall  f1-score   support

       <=50K       0.80      0.96      0.87      5572
        >50K       0.74      0.33      0.46      1969

    accuracy                           0.79      7541
   macro avg       0.77      0.65      0.67      7541
weighted avg       0.79      0.79      0.77      7541

Acc Score 0.7948547937939265


Validation

In [66]:
pre0 = 5337/(5337+1312)
pre1 = 657/(657+235)
rec0 = 5337/(5337+235)
rec1 = 657/(657+1312)
print('Pre0',pre0)
print('Pre1',pre1)
print('Rec0',rec0)
print('Rec1',rec1)

Pre0 0.8026770942998948
Pre1 0.7365470852017937
Rec0 0.9578248384781048
Rec1 0.3336719146775013


In [67]:
f1s0 = 2*pre0*rec0/(pre0+rec0)
f1s1 = 2*pre1*rec1/(pre1+rec1)
print('F1_Score0',f1s0)
print('F1_Score1',f1s1)

F1_Score0 0.8734146141886917
F1_Score1 0.459279972037749


In [68]:
acc = (5337+657)/(5337+235+1312+657)
print('Accuracy',acc)

Accuracy 0.7948547937939265


Percentage of Misclassification

In [69]:
# Misclassification Rate = incorrect predictions / total predictions
# Misclassification Rate = (false positive + false negative) / (total predictions)
MR = (1312+235)/(5337+235+1312+657)
print('Percentage of Misclassification : ',MR*100, '%')

Percentage of Misclassification :  20.514520620607346 %


Conclusion

In [ ]:
The accuracy score of each model is as follows
a. Decision Tree Classifier: 0.8069221588648721
b. Random Forest Classifier: 0.8574459620739955
c. KNN Classifier: 0.7634266012465191
d. Logistic Regression: 0.801617822569951
e. SVM Classifier:0.7948547937939265